### ISSUE TITLE
Installation doesnt work

### ISSUE THREAD

**Issue by FrickX** [TelekomLabs/chef-os-hardening#66]
Hey guys,

awesome work :D

Currently I cant install this nice cookbook.

I've done all the stuff which was in TUTORIAL.md

/usr/local/rvm/gems/ruby-2.2.0/gems/chef-12.0.3/lib/chef/data_bag_item.rb:161: warning: circular argument reference - data_bag
Starting Chef Client, version 12.0.3
Compiling Cookbooks...

Running handlers:
[2015-01-19T20:13:58+01:00] ERROR: Running exception handlers
Running handlers complete
[2015-01-19T20:13:58+01:00] ERROR: Exception handlers complete
[2015-01-19T20:13:58+01:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 1.342882106 seconds
[2015-01-19T20:13:58+01:00] ERROR: Cookbook os-hardening not found. If you're loading os-hardening from another cookbook, make sure you configure the dependency in your metadata
[2015-01-19T20:13:58+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

Ruby version:
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]

Debian 7 x64

Könnt auch auf Deutsch antworten! :)

**Comment by chris-rock** [comment]
@FrickX Thanks for reporting this.

Difficult to say what went wrong. As far as I can see from the logs, chef could not find the cookbook. Could you post the solo.rb? Please ensure the solo.rb is located relative to the cookbooks folder.

If I am not wrong, it looks like you installed chef via gem install (not recommend anymore, but mentioned in our guideline, good catch). For dev environments I recommend [ChefDK](https://downloads.chef.io/chef-dk/). Otherwise you could install chef quickly via `curl -L https://www.chef.io/chef/install.sh | sudo bash`. This has the advantage, that you will have no conflict with ruby versions.

Track update of tutorial.md in #67

**Comment by FrickX** [comment]
Hey Chris,

thx for ur fast response

I've installed at first Chef via the link but it didnt worked too.

After that ive installed it via the gem Command and as you can see didnt worked too.

My directory structure:

cookbooks (the directory)
solo.json
solo.rb


solo.rb:

root@debian:~# head solo.rb
cookbook_path "cookbooks"

**Comment by chris-rock** [comment]
@FrickX I updated the tutorial. Please take a look here: https://github.com/TelekomLabs/chef-os-hardening/pull/68/files?diff=unified&short_path=81a7b83 Let me know if that worked. We will add some more information for production deployments

**Comment by FrickX** [comment]
@chris-rock The new tutorial works like a charm. Thx for your help :) :+1:

**Comment by chris-rock** [comment]
great to hear that worked. Please let us know, if you have any questions
